const features = [
  {
    icon: '🤖',
    title: 'AI-Powered Questions',
    description:
      'Get unique interview questions generated by AI, tailored to your target role, industry, and experience level.',
  },
  {
    icon: '📝',
    title: 'Personalized Feedback',
    description:
      'Receive detailed analysis of your answers with specific strengths, areas for improvement, and actionable tips.',
  },
  {
    icon: '⭐',
    title: 'STAR Framework Coaching',
    description:
      'For behavioral questions, get scored on each STAR element — Situation, Task, Action, and Result.',
  },
  {
    icon: '📄',
    title: 'Resume-Based Personalization',
    description:
      'Upload your resume or enter your background to get questions and feedback matched to your career profile.',
  },
  {
    icon: '💼',
    title: 'Job Description Mode',
    description:
      'Paste a job description to generate interview questions specifically tailored to that role.',
  },
  {
    icon: '🎯',
    title: 'Multiple Question Types',
    description:
      'Practice behavioral, open-ended case, and situational judgment questions across Easy, Medium, and Hard difficulty levels.',
  },
];

export default function Features() {
  return (
    <section className="py-20 bg-white">
      <div className="mx-auto max-w-6xl px-4">
        <h2 className="text-center text-3xl font-bold text-gray-900">
          Everything You Need to Prepare
        </h2>
        <p className="mx-auto mt-4 max-w-2xl text-center text-gray-600">
          A comprehensive interview preparation toolkit powered by AI
        </p>
        <div className="mt-16 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((feature) => (
            <div
              key={feature.title}
              className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm hover:shadow-md transition-shadow"
            >
              <div className="text-3xl">{feature.icon}</div>
              <h3 className="mt-4 text-lg font-semibold text-gray-900">
                {feature.title}
              </h3>
              <p className="mt-2 text-sm leading-6 text-gray-600">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
